//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AflyatunovAutoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entering
    {
        public string ID { get; set; }
        public string Login { get; set; }
        public string Passsword { get; set; }
        public string Who { get; set; }
    }
}
