//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AflyatunovAutoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posishen
    {
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Cost { get; set; }
        public string WeightOrVolume { get; set; }
        public string MainImagePath { get; set; }
    }
}
