//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AflyatunovAutoservice
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientService = new HashSet<ClientService>();
            this.ServicePhoto = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Name_of_the_service { get; set; }
        public string Main_Image { get; set; }
        public short Duration { get; set; }
        public decimal Cost { get; set; }
        public Nullable<double> Current_discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhoto { get; set; }

        public string OldCost
        {
            get
            {
                if (Current_discount > 0)
                {
                    return Cost.ToString();
                }
                else
                {
                    return "";
                }
            }
        }
        public decimal NewCost
        {
            get
            {
                if(Current_discount > 0)
                {
                    return((decimal)Cost - (decimal)Cost * (decimal)Current_discount/100);
                }
                else
                {
                    return (decimal)Cost;
                }
            }
        }
        public SolidColorBrush FonStyle
        {
            get
            {
                if (Current_discount > 0)
                {
                    return(SolidColorBrush) new BrushConverter().ConvertFromString("LightGreen");
                }
                else
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                }
            }
        }
        
    }

}
